import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { UserPlus } from 'lucide-react'

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/Dialog'
import { Button } from '@/components/ui/Button'
import { Input } from '@/components/ui/Input'
import { Label } from '@/components/ui/Label'
import { cn } from '@/utils/cn'
import type { UserCreateRequest } from '../types/user.types'

// ── Zod schema ────────────────────────────────────────────────
const schema = z.object({
  name: z.string().min(1, 'Name is required').max(100, 'Max 100 characters'),
  email: z
    .string()
    .min(1, 'Email is required')
    .email('Must be a valid email')
    .max(150, 'Max 150 characters'),
  password: z
    .string()
    .min(8, 'Must be at least 8 characters')
    .max(100, 'Max 100 characters'),
  phone: z.string().max(20, 'Max 20 characters').optional().or(z.literal('')),
  designation: z.string().max(100, 'Max 100 characters').optional().or(z.literal('')),
  roleName: z.enum(['ADMIN', 'HR', 'HR_MANAGER', 'MANAGER', 'DIRECTOR', 'EMPLOYEE'] as const, {
    required_error: 'Role is required',
  }),
  employmentType: z
    .enum(['FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN'] as const)
    .optional()
    .or(z.literal('')),
  joiningDate: z.string().optional().or(z.literal('')),
  departmentId: z.coerce.number().positive().optional().or(z.literal('')),
  managerId: z.string().uuid('Must be a valid user ID').optional().or(z.literal('')),
})

type FormValues = z.infer<typeof schema>

// ── Props ─────────────────────────────────────────────────────
interface UserCreateModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  onSubmit: (data: UserCreateRequest) => Promise<boolean>
  departments?: { id: number; name: string }[]
  users?: { id: string; name: string; employeeId: string; roleName: string }[]
}

// ── Shared field styles ───────────────────────────────────────
const fieldClass = 'space-y-1.5'
const errorClass = 'text-xs text-destructive mt-1'
const selectClass =
  'flex h-10 w-full rounded-lg border border-input bg-background px-3 py-2 text-sm ' +
  'ring-offset-background focus:outline-none focus:ring-2 focus:ring-ring ' +
  'focus:ring-offset-1 transition-colors disabled:opacity-50'

// ── Component ─────────────────────────────────────────────────
export function UserCreateModal({ open, onOpenChange, onSubmit, departments = [], users = [] }: UserCreateModalProps) {
  const {
    register,
    handleSubmit,
    reset,
    formState: { errors, isSubmitting },
  } = useForm<FormValues>({
    resolver: zodResolver(schema),
    defaultValues: {
      name: '',
      email: '',
      password: '',
      phone: '',
      designation: '',
      roleName: undefined,
      employmentType: '',
      joiningDate: '',
      departmentId: '',
      managerId: '',
    },
  })

  const handleFormSubmit = async (values: FormValues) => {
    const payload: UserCreateRequest = {
      name: values.name,
      email: values.email,
      password: values.password,
      roleName: values.roleName,
      ...(values.phone && { phone: values.phone }),
      ...(values.designation && { designation: values.designation }),
      ...(values.joiningDate && { joiningDate: values.joiningDate }),
      ...(values.departmentId && typeof values.departmentId === 'number'
        ? { departmentId: values.departmentId }
        : {}),
      ...(values.employmentType
        ? { employmentType: values.employmentType as UserCreateRequest['employmentType'] }
        : {}),
      ...(values.managerId ? { managerId: values.managerId } : {}),
    }
    const ok = await onSubmit(payload)
    if (ok) {
      reset()
      onOpenChange(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-xl">
        <DialogHeader>
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-emerald-500 to-teal-600 shadow-md shadow-emerald-500/25 mb-1">
            <UserPlus className="h-5 w-5 text-white" />
          </div>
          <DialogTitle>Create New User</DialogTitle>
          <DialogDescription>
            Fill in the details below to add a new team member.
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit(handleFormSubmit)} noValidate>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {/* Employee ID — auto-generated by the system */}
            <div className={fieldClass}>
              <Label>Employee ID</Label>
              <div className="flex h-10 w-full items-center rounded-lg border border-input bg-muted/50 px-3 text-sm text-muted-foreground select-none">
                Auto-generated (e.g. EMP-0001)
              </div>
            </div>

            {/* Name */}
            <div className={fieldClass}>
              <Label htmlFor="name">Full Name *</Label>
              <Input
                id="name"
                placeholder="John Doe"
                error={!!errors.name}
                {...register('name')}
              />
              {errors.name && <p className={errorClass}>{errors.name.message}</p>}
            </div>

            {/* Email */}
            <div className={cn(fieldClass, 'sm:col-span-2')}>
              <Label htmlFor="email">Email *</Label>
              <Input
                id="email"
                type="email"
                placeholder="john@company.com"
                error={!!errors.email}
                {...register('email')}
              />
              {errors.email && <p className={errorClass}>{errors.email.message}</p>}
            </div>

            {/* Password */}
            <div className={cn(fieldClass, 'sm:col-span-2')}>
              <Label htmlFor="password">Password *</Label>
              <Input
                id="password"
                type="password"
                placeholder="Min. 8 characters"
                error={!!errors.password}
                {...register('password')}
              />
              {errors.password && <p className={errorClass}>{errors.password.message}</p>}
            </div>

            {/* Role */}
            <div className={fieldClass}>
              <Label htmlFor="roleName">Role *</Label>
              <select
                id="roleName"
                className={cn(selectClass, errors.roleName && 'border-destructive')}
                {...register('roleName')}
              >
                <option value="">Select role…</option>
                <option value="ADMIN">Admin</option>
                <option value="HR">HR</option>
                <option value="HR_MANAGER">HR Manager</option>
                <option value="MANAGER">Manager</option>
                <option value="DIRECTOR">Director</option>
                <option value="EMPLOYEE">Employee</option>
              </select>
              {errors.roleName && <p className={errorClass}>{errors.roleName.message}</p>}
            </div>

            {/* Employment Type */}
            <div className={fieldClass}>
              <Label htmlFor="employmentType">Employment Type</Label>
              <select
                id="employmentType"
                className={selectClass}
                {...register('employmentType')}
              >
                <option value="">Select type…</option>
                <option value="FULL_TIME">Full Time</option>
                <option value="PART_TIME">Part Time</option>
                <option value="CONTRACT">Contract</option>
                <option value="INTERN">Intern</option>
              </select>
            </div>

            {/* Designation */}
            <div className={fieldClass}>
              <Label htmlFor="designation">Designation</Label>
              <Input
                id="designation"
                placeholder="Software Engineer"
                {...register('designation')}
              />
            </div>

            {/* Phone */}
            <div className={fieldClass}>
              <Label htmlFor="phone">Phone</Label>
              <Input id="phone" placeholder="+1 555 000 0000" {...register('phone')} />
            </div>

            {/* Department */}
            <div className={fieldClass}>
              <Label htmlFor="departmentId">Department</Label>
              <select
                id="departmentId"
                className={selectClass}
                {...register('departmentId')}
              >
                <option value="">— Select department —</option>
                {departments.map((d) => (
                  <option key={d.id} value={d.id}>{d.name}</option>
                ))}
              </select>
            </div>

            {/* Reporting Manager */}
            <div className={fieldClass}>
              <Label htmlFor="managerId">Reporting Manager</Label>
              <select
                id="managerId"
                className={selectClass}
                {...register('managerId')}
              >
                <option value="">— Select manager —</option>
                {users
                  .filter((u) => u.roleName === 'MANAGER' || u.roleName === 'HR_MANAGER' || u.roleName === 'DIRECTOR' || u.roleName === 'ADMIN' || u.roleName === 'HR')
                  .map((u) => (
                    <option key={u.id} value={u.id}>{u.name} ({u.employeeId})</option>
                  ))}
              </select>
            </div>

            {/* Joining Date */}
            <div className={fieldClass}>
              <Label htmlFor="joiningDate">Joining Date</Label>
              <Input id="joiningDate" type="date" {...register('joiningDate')} />
            </div>
          </div>

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={() => {
                reset()
                onOpenChange(false)
              }}
            >
              Cancel
            </Button>
            <Button
              type="submit"
              loading={isSubmitting}
              className="bg-gradient-to-r from-emerald-500 to-teal-600 hover:from-emerald-600 hover:to-teal-700 text-white border-0"
            >
              Create User
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}
