#!/bin/bash

# Script to generate Render environment variables with correct SSL parameters
# Usage: ./generate-render-env.sh

echo "=================================================="
echo "RENDER ENVIRONMENT VARIABLES FOR TMS-BACKEND"
echo "=================================================="
echo ""
echo "Copy and paste these into Render Environment settings:"
echo ""
echo "---------------------------------------------------"
echo "SPRING_DATASOURCE_URL"
echo "---------------------------------------------------"
echo "jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/tms?sslMode=VERIFY_IDENTITY&requireSSL=true&enabledTLSProtocols=TLSv1.2,TLSv1.3&serverTimezone=UTC&createDatabaseIfNotExist=true"
echo ""
echo "---------------------------------------------------"
echo "SPRING_DATASOURCE_USERNAME"
echo "---------------------------------------------------"
echo "2n8ARf4DxRuab3Z.root"
echo ""
echo "---------------------------------------------------"
echo "SPRING_DATASOURCE_PASSWORD"
echo "---------------------------------------------------"
echo "Qc46tGD6PmHH03C8"
echo ""
echo "---------------------------------------------------"
echo "JWT_SECRET"
echo "---------------------------------------------------"
echo "dG1zLWp3dC1zZWNyZXQta2V5LXZlcnktc2VjdXJlLW1pbi0zMi1jaGFycw=="
echo ""
echo "---------------------------------------------------"
echo "FRONTEND_URL"
echo "---------------------------------------------------"
echo "https://tms-lac.vercel.app"
echo ""
echo "---------------------------------------------------"
echo "SPRING_MAIL_USERNAME"
echo "---------------------------------------------------"
echo "milisrivastava.zucitech@gmail.com"
echo ""
echo "---------------------------------------------------"
echo "SPRING_MAIL_PASSWORD"
echo "---------------------------------------------------"
echo "tnlg uznn cbls pbwl"
echo ""
echo "=================================================="
echo "IMPORTANT CHECKS:"
echo "=================================================="
echo "✓ SPRING_DATASOURCE_URL includes 'sslMode=VERIFY_IDENTITY'"
echo "✓ SPRING_DATASOURCE_URL includes 'requireSSL=true'"
echo "✓ SPRING_DATASOURCE_URL includes 'enabledTLSProtocols=TLSv1.2,TLSv1.3'"
echo "✓ No line breaks or extra spaces in any value"
echo "✓ Click 'Save Changes' after adding each variable"
echo "✓ Use 'Manual Deploy' to trigger a new deployment"
echo ""
